-- DML
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS book;

CREATE TABLE IF NOT EXISTS book (
    id BIGSERIAL NOT NULL,
    isbn VARCHAR(255),
    title VARCHAR(255),
    status VARCHAR(255),
    PRIMARY KEY (id));