-- DML
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS author;

CREATE TABLE IF NOT EXISTS author (
    id BIGSERIAL NOT NULL,
    age INT4 NOT NULL,
    genre VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS book (
    id BIGSERIAL NOT NULL,
    isbn VARCHAR(255),
    title VARCHAR(255),
    price INT4,
    author_id INT8,
    PRIMARY KEY (id));
ALTER TABLE book ADD CONSTRAINT FK_AUTHOR FOREIGN KEY (author_id) REFERENCES author(id);